export const INTEGRATION_LOGOS = [
  { slug: "gmail", name: "Gmail" },
  { slug: "github", name: "GitHub" },
  { slug: "notion", name: "Notion" },
  { slug: "figma", name: "Figma" },
  { slug: "linear", name: "Linear" },
  { slug: "jira", name: "Jira" },
  { slug: "discord", name: "Discord" },
  { slug: "googledrive", name: "Google Drive" },
  { slug: "googlecalendar", name: "Google Calendar" },
  { slug: "todoist", name: "Todoist" },
  { slug: "asana", name: "Asana" },
  { slug: "trello", name: "Trello" },
  { slug: "stripe", name: "Stripe" },
  { slug: "hubspot", name: "HubSpot" },
  { slug: "airtable", name: "Airtable" },
  { slug: "slack", name: "Slack" },
  { slug: "dropbox", name: "Dropbox" },
  { slug: "telegram", name: "Telegram" },
] as const;
